# Generated by Django 5.0.7 on 2025-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
